<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\DB;

class TokenDelete extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'app:token-delete';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'This command will delete the Token every day that is generated by user while login';

    /**
     * Execute the console command.
     */
    public function handle()
    {
        DB::table('personal_access_tokens')->delete();
        $this->info("Successfully Deleted Token");
    }
}
